"""Direct pyoomph template for the explicit Anthony structured Q2 graph.

The geometry and connectivity are generated by :mod:`structured_blocks` and
fed to ``MeshedMeshTemplate`` without Gmsh.  Topological node keys are kept
alongside the pyoomph template indices so a later remeshing/integration layer
can recover the graph identity without a coordinate lookup.
"""

from __future__ import annotations

from collections.abc import Callable
import json
from typing import Any

from pyoomph.meshes.mesh import MeshedMeshTemplate

from .structured_blocks import (
    BoundaryFacet,
    Grading,
    MeshNode,
    NodeKey,
    Q2Element,
    StructuredQ2Graph,
    build_initial_four_patch_graph,
    validate_resolution,
)


# structured_blocks uses [SW, SE, NE, NW, S, E, N, W, C].  The pyoomph
# MeshTemplate C2 API uses row-major [SW, S, SE, W, C, E, NW, N, NE].
GRAPH_TO_PYOOMPH_Q2: tuple[int, ...] = (0, 4, 1, 7, 8, 5, 3, 6, 2)
_STATE_GRAPH_VERSION = 1


def _graph_state_payload(graph: StructuredQ2Graph) -> str:
    """Return the restart-relevant mapped graph as deterministic JSON."""
    payload = {
        "version": _STATE_GRAPH_VERSION,
        "R0": graph.R0,
        "Z0": graph.Z0,
        "nodes": [
            [
                list(key),
                list(node.coordinates),
                sorted(node.patches),
                [[patch, list(point)] for patch, point in sorted(node.logical_coordinates.items())],
            ]
            for key, node in sorted(graph.nodes.items())
        ],
        "elements": [
            [
                list(element.element_id),
                element.patch_id,
                list(element.local_index),
                [list(key) for key in element.node_keys],
                [list(point) for point in element.reference_coordinates],
            ]
            for element in graph.elements
        ],
        "boundary_facets": {
            name: [
                [
                    list(facet.facet_id),
                    facet.patch_id,
                    list(facet.element_id),
                    facet.side,
                    facet.edge_id,
                    facet.orientation,
                    [list(key) for key in facet.node_keys],
                ]
                for facet in facets
            ]
            for name, facets in sorted(graph.boundary_facets.items())
        },
        "shared_node_keys": [list(key) for key in sorted(graph.shared_node_keys)],
        "vertices": {name: list(key) for name, key in sorted(graph.vertices.items())},
        "hit_parameter": graph.hit_parameter,
        "divider_hit": list(graph.divider_hit),
        "cap_resolution": graph.cap_resolution,
        "bridge_normal_resolution": graph.bridge_normal_resolution,
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False)


def _graph_from_state_payload(encoded: str) -> StructuredQ2Graph:
    """Rebuild the graph subset used by template recreation and later remeshes."""
    payload: dict[str, Any] = json.loads(encoded)
    if payload.get("version") != _STATE_GRAPH_VERSION:
        raise RuntimeError("unsupported Anthony mapped-graph state version")
    nodes = {}
    for raw_key, coordinates, patches, logical in payload["nodes"]:
        key = tuple(int(value) for value in raw_key)
        nodes[key] = MeshNode(
            key,
            tuple(float(value) for value in coordinates),
            {int(value) for value in patches},
            {
                int(patch): tuple(float(value) for value in point)
                for patch, point in logical
            },
        )
    elements = tuple(
        Q2Element(
            tuple(int(value) for value in element_id),
            int(patch_id),
            tuple(int(value) for value in local_index),
            tuple(tuple(int(value) for value in key) for key in node_keys),
            tuple(tuple(float(value) for value in point) for point in reference_coordinates),
        )
        for element_id, patch_id, local_index, node_keys, reference_coordinates
        in payload["elements"]
    )
    boundary_facets = {
        name: tuple(
            BoundaryFacet(
                tuple(int(value) for value in facet_id),
                int(patch_id),
                tuple(int(value) for value in element_id),
                str(side),
                int(edge_id),
                int(orientation),
                tuple(tuple(int(value) for value in key) for key in node_keys),
            )
            for facet_id, patch_id, element_id, side, edge_id, orientation, node_keys
            in facets
        )
        for name, facets in payload["boundary_facets"].items()
    }
    return StructuredQ2Graph(
        R0=float(payload["R0"]),
        Z0=float(payload["Z0"]),
        nodes=nodes,
        elements=elements,
        boundary_facets=boundary_facets,
        # Patch maps and analytical edges are construction aids.  Runtime
        # remeshing is keyed by the explicit nodes/elements/facets above.
        patches={},
        shared_node_keys=frozenset(
            tuple(int(value) for value in key) for key in payload["shared_node_keys"]
        ),
        vertices={
            name: tuple(int(value) for value in key)
            for name, key in payload["vertices"].items()
        },
        edges={},
        hit_parameter=float(payload["hit_parameter"]),
        divider_hit=tuple(float(value) for value in payload["divider_hit"]),
        cap_resolution=int(payload["cap_resolution"]),
        bridge_normal_resolution=int(payload["bridge_normal_resolution"]),
    )


class AnthonyMappedQuadMesh(MeshedMeshTemplate):
    """A resolution-controlled four-patch C2 mesh built from graph keys.

    ``R0`` and ``Z0`` are nondimensional.  The default ``Z0`` is Anthony's
    approximate point-contact value.  All nodes are passed through
    :meth:`MeshTemplate.add_node`, never ``add_node_unique``; graph topology,
    rather than a coordinate tolerance, determines sharing.
    """

    domain_name = "drop"

    def __init__(
        self,
        R0: float,
        Z0: float | None = None,
        *,
        cap_resolution: int = 1,
        bridge_normal_resolution: int = 2,
        grading_u: Grading | Callable[[float], float] | None = None,
        grading_v: Grading | Callable[[float], float] | None = None,
    ) -> None:
        super().__init__()
        self.R0 = float(R0)
        self.Z0 = None if Z0 is None else float(Z0)
        self.cap_resolution = validate_resolution(cap_resolution, "cap_resolution")
        self.bridge_normal_resolution = validate_resolution(
            bridge_normal_resolution, "bridge_normal_resolution"
        )
        self.grading_u = grading_u
        self.grading_v = grading_v
        self.graph: StructuredQ2Graph | None = None
        self.node_key_to_template_index: dict[NodeKey, int] = {}
        # Descriptive aliases are kept for diagnostics and future remeshing.
        self.template_index_by_key = self.node_key_to_template_index
        self.template_element_indices: dict[tuple[int, int, int], tuple[int, ...]] = {}
        self.template_boundary_facets: dict[str, tuple[tuple[int, ...], ...]] = {}
        # A recreation remesh must be prepared by the problem before pyoomph
        # resets this template.  The attribute survives ``MeshTemplate._reset``
        # and is deliberately not consumed here: it remains available while
        # the transaction-bound interpolator is constructed.
        self.pending_remesh_graph: StructuredQ2Graph | None = None
        self._restart_graph: StructuredQ2Graph | None = None
        self.remesh_rmin_baseline = self.R0
        self.remesh_abs2h_baseline: float | None = None
        self.automatic_remesh_calibration_payload: dict[str, Any] | None = None
        self.automatic_remesh_accepted_marker: dict[str, Any] | None = None
        self.automatic_remesh_events = 0
        self._restart_slot_one: tuple[tuple[NodeKey, tuple[float, ...], tuple[float, ...]], ...] | None = None

    def prepare_remesh_graph(self, graph: StructuredQ2Graph) -> None:
        if self.pending_remesh_graph is not None:
            raise RuntimeError("a mapped remesh graph is already pending")
        self.pending_remesh_graph = graph

    def clear_remesh_graph(self) -> None:
        self.pending_remesh_graph = None

    def restore_restart_slot_one(self, mesh: Any) -> None:
        """Restore histories pyoomph rewrites for pinned nodes during load."""
        if self._restart_slot_one is None:
            return
        from .runtime_remesh import _runtime_nodes_by_template_index

        runtime_nodes = _runtime_nodes_by_template_index(self, mesh)
        for key, positions, values in self._restart_slot_one:
            index = self.node_key_to_template_index[key]
            node = runtime_nodes[index]
            if len(positions) != node.ndim() or len(values) != node.nvalue():
                raise RuntimeError("restart slot-one schema differs from the rebuilt mesh")
            for component, value in enumerate(positions):
                node.set_x_at_t(1, component, value)
            for value_index, value in enumerate(values):
                node.set_value_at_t(1, value_index, value)
        self._restart_slot_one = None

    def define_geometry(self) -> None:
        first_time = self.is_first_time()
        if not first_time and self.pending_remesh_graph is not None:
            graph = self.pending_remesh_graph
        elif self._restart_graph is not None:
            graph = self._restart_graph
            # State replacement is the sole consumer.  A later recreation
            # must again require an explicitly prepared remesh graph.
            self._restart_graph = None
        elif first_time:
            graph = build_initial_four_patch_graph(
                self.R0,
                self.Z0,
                cap_resolution=self.cap_resolution,
                bridge_normal_resolution=self.bridge_normal_resolution,
                grading_u=self.grading_u,
                grading_v=self.grading_v,
            )
        else:
            raise RuntimeError(
                "AnthonyMappedQuadMesh recreation has no prepared remesh graph"
            )
        self.cap_resolution = graph.cap_resolution
        self.bridge_normal_resolution = graph.bridge_normal_resolution
        self.graph = graph
        self.node_key_to_template_index = {}
        self.template_index_by_key = self.node_key_to_template_index
        self.template_element_indices = {}
        self.template_boundary_facets = {}

        # Sorting integer keys makes the template index assignment independent
        # of dictionary insertion details while retaining every graph node.
        for key in sorted(graph.nodes):
            x, y = graph.nodes[key].coordinates
            self.node_key_to_template_index[key] = int(self.add_node(x, y))

        domain = self.new_domain(self.domain_name)
        domain.set_nodal_dimension(2)
        domain.set_lagrangian_dimension(2)
        for element in graph.elements:
            graph_indices = tuple(self.node_key_to_template_index[key] for key in element.node_keys)
            pyoomph_indices = tuple(graph_indices[index] for index in GRAPH_TO_PYOOMPH_Q2)
            domain.add_quad_2d_C2(*pyoomph_indices)
            self.template_element_indices[element.element_id] = pyoomph_indices

        # The graph stores both sides of the divider so adjacency is visible
        # to pure-Python callers.  MeshTemplate facets are set keyed by their
        # corner vertices; register each topological facet once here, passing
        # all three Q2 nodes and the two corner vertices separately.
        for label in ("axis", "plane", "interface", "divider"):
            seen: set[tuple[int, ...]] = set()
            registered: list[tuple[int, ...]] = []
            for facet in graph.boundary_facets.get(label, ()):
                all_indices = tuple(self.node_key_to_template_index[key] for key in facet.node_keys)
                identity = tuple(sorted(all_indices))
                if identity in seen:
                    continue
                seen.add(identity)
                registered.append(all_indices)
                corner_indices = [all_indices[0], all_indices[-1]]
                self.add_facet_to_boundary(label, list(all_indices), corner_indices)
            self.template_boundary_facets[label] = tuple(registered)

        # The divider is an internal interface between the bridge and cap
        # elements, despite being represented by a named facet set.
        self.set_boundary_as_interior("divider")

    def _define_state_file(self, state, additional_info={}):
        """Persist the in-memory graph that generic mesh state cannot identify."""
        active = super()._define_state_file(state, additional_info=additional_info)
        if state.save:
            if self.graph is None:
                raise RuntimeError("cannot save an undefined Anthony mapped graph")
            payload = json.loads(_graph_state_payload(self.graph))
            from .runtime_remesh import _runtime_nodes_by_template_index

            mesh = self.get_problem().get_mesh(self.domain_name)
            runtime_nodes = _runtime_nodes_by_template_index(self, mesh)
            payload["restart_slot_one"] = [
                [
                    list(key),
                    [float(node.x_at_t(1, component)) for component in range(node.ndim())],
                    [float(node.value_at_t(1, index)) for index in range(node.nvalue())],
                ]
                for key, index in sorted(self.node_key_to_template_index.items())
                for node in (runtime_nodes[index],)
            ]
            payload["remesh_rmin_baseline"] = float(self.remesh_rmin_baseline)
            payload["remesh_abs2h_baseline"] = self.remesh_abs2h_baseline
            payload["automatic_remesh_calibration"] = (
                self.automatic_remesh_calibration_payload
            )
            payload["automatic_remesh_accepted_marker"] = (
                self.automatic_remesh_accepted_marker
            )
            payload["automatic_remesh_events"] = int(self.automatic_remesh_events)
            encoded = json.dumps(
                payload, sort_keys=True, separators=(",", ":"), allow_nan=False
            )
        else:
            encoded = ""
        encoded = state.string_data(lambda: encoded, lambda value: value)
        if state.save:
            return active

        payload = json.loads(encoded)
        stored_graph = _graph_from_state_payload(encoded)
        self.remesh_rmin_baseline = float(
            payload.get("remesh_rmin_baseline", stored_graph.R0)
        )
        stored_abs2h = payload.get("remesh_abs2h_baseline")
        self.remesh_abs2h_baseline = (
            None if stored_abs2h is None else float(stored_abs2h)
        )
        self.automatic_remesh_calibration_payload = payload.get(
            "automatic_remesh_calibration"
        )
        self.automatic_remesh_accepted_marker = payload.get(
            "automatic_remesh_accepted_marker"
        )
        self.automatic_remesh_events = int(payload.get("automatic_remesh_events", 0))
        self._restart_slot_one = tuple(
            (
                tuple(int(value) for value in key),
                tuple(float(value) for value in positions),
                tuple(float(value) for value in values),
            )
            for key, positions, values in payload.get("restart_slot_one", ())
        )
        if (
            self.graph is not None
            and _graph_state_payload(self.graph) == _graph_state_payload(stored_graph)
        ):
            return active

        replacement = AnthonyMappedQuadMesh(
            stored_graph.R0,
            stored_graph.Z0,
            cap_resolution=stored_graph.cap_resolution,
            bridge_normal_resolution=stored_graph.bridge_normal_resolution,
            grading_u=self.grading_u,
            grading_v=self.grading_v,
        )
        replacement._restart_graph = stored_graph
        replacement.remesh_rmin_baseline = self.remesh_rmin_baseline
        replacement.remesh_abs2h_baseline = self.remesh_abs2h_baseline
        replacement.automatic_remesh_calibration_payload = (
            self.automatic_remesh_calibration_payload
        )
        replacement.automatic_remesh_accepted_marker = (
            self.automatic_remesh_accepted_marker
        )
        replacement.automatic_remesh_events = self.automatic_remesh_events
        replacement._restart_slot_one = self._restart_slot_one
        replacement.remesher = self.remesher
        if replacement.remesher is not None:
            replacement.remesher.template = replacement
        replacement._do_define_geometry(self.get_problem())
        self._template_override = replacement
        return replacement


__all__ = [
    "AnthonyMappedQuadMesh",
    "GRAPH_TO_PYOOMPH_Q2",
    "_graph_from_state_payload",
    "_graph_state_payload",
]
